# Site
name: "codercoder"
title: "codercoder"
description: "DBA(Database Administrator), we can share and discuss MySQL, MongoDB, Redis and other databases here, also including learning Python, Shell, Golang together."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'G-M7T9WZVF2S'
google_ad_client: 'ca-pub-7247428138349290'
disqus: 'demowebsite'
include: ["_pages"]
permalink: /:title/

Authors:
authors:
  Shuo:
    name: Shuo
    display_name: Shuo
    avatar: 'assets/images/Shuo.png'
    email: wangshuoshuo45@qq.com
    linkedin: https://www.linkedin.com/in/shuo-wang-b4557b102/
    web: https://codercoder.cn/about
    description: "I'm a DBA(Database Administrator), we can share and discuss MySQL, MongoDB, Redis and other databases here, also including learning Python, Shell, Golang together."

  Smile:
    name: Smile
    display_name: Smile    
    avatar: 'assets/images/liyao.png'
    email: 962205674@qq.com
    web: https://codercoder.cn/about
    description: "I'm a Java developer."

  rondon:
    name: rondon
    display_name: rondon    
    avatar: 'assets/images/rondon.png'
    email: rondon@vip.qq.com
    web: https://codercoder.cn/about
    description: "I'm a Oracle DBA(Database Administrator)."

  Janvn:
    name: Janvn
    display_name: Janvn    
    avatar: 'assets/images/Janvn.png'
    email: 287234973@qq.com
    web: https://codercoder.cn/about
    description: "I'm a Bigdata developer."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
